services:
  geoipupdate:
    image: maxmindinc/geoipupdate
    restart: unless-stopped
    environment:
      GEOIPUPDATE_ACCOUNT_ID: ${GEOIPUPDATE_ACCOUNT_ID}
      GEOIPUPDATE_LICENSE_KEY: ${GEOIPUPDATE_LICENSE_KEY}
      GEOIPUPDATE_EDITION_IDS: ${GEOIPUPDATE_EDITION_IDS}
      GEOIPUPDATE_FREQUENCY: ${GEOIPUPDATE_FREQUENCY}
    volumes:
      - ${GEOIP_DB_DIRECTORY}:/usr/share/GeoIP
    networks:
      - nym-bity

networks:
  nym-bity:
