name: "Test"

on:
  push:
    paths-ignore:
      # if only changes in assets/* don't run these jobs (useless)
      - "assets/**"
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - name: Lint
        run: cargo clippy
      - name: Check
        run: cargo check
